#!/usr/bin/env bash
# Validates the committed corpus reports that back this repository's README
# badges (`.adrkit/lint.json`, `.adrkit/queue.json`).
#
# adrkit ships no badge service and no `adr badge` command: both badges are a
# recipe over JSON the CLI already emits, rendered by shields.io from a URL the
# adopter serves (adrkit ADR-0025, https://adrkit.dev/badges/). That makes the
# committed JSON a *claim about this corpus* published to a third party, so it
# is validated like every other claim here rather than trusted to stay true.
#
# Why the files are committed rather than regenerated by a bot:
#
#   The upstream recipe adds a workflow holding `contents: write` that pushes
#   regenerated reports to the default branch on every corpus change. This
#   repository deliberately does not do that. Its corpus is a frozen fixture
#   set with deterministic expectations (scripts/assert-queue-report.ts), so the
#   reports change only when someone edits docs/adr on purpose -- and editing
#   docs/adr already obliges them to update assertions in the same change. A
#   write-capable workflow would therefore add a token that can push to `main`
#   in exchange for automating something that must not happen automatically.
#   Asserting the committed files are current is strictly stronger than
#   regenerating them: a stale report fails the build instead of being silently
#   corrected after the fact.
#
# Why `--as-of` is pinned here but not in the published recipe:
#
#   `adr queue` defaults `--as-of` to today, which would make the committed
#   queue.json differ from a regeneration every single day and turn this check
#   into noise. This repository already pins a fixed date for the same reason in
#   scripts/validate-queue.sh. The badge reads `$.totalItems`, which is selected
#   by `status: proposed` and is therefore independent of the date -- observed,
#   not assumed: at --as-of 2026-01-01, 2026-07-21, and 2027-12-31 totalItems is
#   3 in all three, while slaState moves within-sla -> overdue/due -> overdue.
#   The SLA fields in the committed file are consequently true as of ASOF below
#   and are NOT a live view; nothing renders them and README.md says so.
#
# What it does:
#   1. Cross-checks its adrkit pin against scripts/validate-queue.sh.
#   2. Builds adrkit at that pin (or reuses a prebuilt CLI via ADR_CLI, so a
#      caller that already built one does not pay for it twice).
#   3. Regenerates both reports into a temporary directory and requires them to
#      be byte-identical to the committed files.
#   4. Asserts the two fields the badge URLs actually dereference are present
#      and are integers -- the failure the upstream guide calls out, where a
#      truncated or malformed write renders as `no result` on the badge and
#      reads to a visitor as a bug in the tooling.
#
# Nothing here writes to the corpus and nothing is committed. The only network
# access is the pinned shallow fetch in step 2, skipped entirely under ADR_CLI.
set -euo pipefail

# Kept in sync with scripts/validate-queue.sh; the cross-check below fails the
# build if they drift. See README.md ("Pinned adrkit commit") — never a branch
# or tag.
ADRKIT_REF="d9ce9e18fbe95525b4e3b2780bfe33352a5ab7f2"
ADRKIT_REPO="${ADRKIT_REPO:-https://github.com/mbeacom/adrkit.git}"

# Must match scripts/validate-queue.sh's AS_OF. Cross-checked below rather than
# trusted, because a silent divergence would make the committed queue.json
# disagree with the report this repository's own queue evidence is built from.
ASOF="2026-07-21"

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
REPORT_DIR="${REPO_ROOT}/.adrkit"

WORKDIR="$(mktemp -d)"
cleanup() { rm -rf "${WORKDIR}"; }
trap cleanup EXIT

FAILURES=0
pass() { echo "ok   $1  $2"; }
fail() { echo "FAIL $1  $2" >&2; FAILURES=$((FAILURES + 1)); }

echo "==> Cross-checking the adrkit pin against scripts/validate-queue.sh"
QUEUE_REF="$(sed -n 's/^ADRKIT_REF="\([0-9a-f]\{40\}\)"$/\1/p' \
  "${REPO_ROOT}/scripts/validate-queue.sh" | head -n 1)"
if [[ -z "${QUEUE_REF}" ]]; then
  echo "error: could not extract ADRKIT_REF from scripts/validate-queue.sh" >&2
  echo "The cross-check cannot be silently skipped; fix the extraction." >&2
  exit 1
fi
if [[ "${QUEUE_REF}" != "${ADRKIT_REF}" ]]; then
  echo "error: adrkit pin disagreement between validation scripts" >&2
  echo "  validate-badge-reports.sh: ${ADRKIT_REF}" >&2
  echo "  validate-queue.sh:         ${QUEUE_REF}" >&2
  exit 1
fi
echo "both validation scripts pin ${ADRKIT_REF}"

# The as-of date is duplicated for the same reason the SHA is, and drifts the
# same way. Extracted mechanically rather than compared by eye.
QUEUE_ASOF="$(sed -n 's/^AS_OF="\${ADR_QUEUE_AS_OF:-\([0-9-]\{10\}\)}"$/\1/p' \
  "${REPO_ROOT}/scripts/validate-queue.sh" | head -n 1)"
if [[ -z "${QUEUE_ASOF}" ]]; then
  echo "error: could not extract AS_OF from scripts/validate-queue.sh" >&2
  exit 1
fi
if [[ "${QUEUE_ASOF}" != "${ASOF}" ]]; then
  echo "error: as-of disagreement between validation scripts" >&2
  echo "  validate-badge-reports.sh: ${ASOF}" >&2
  echo "  validate-queue.sh:         ${QUEUE_ASOF}" >&2
  exit 1
fi
echo "both validation scripts use as-of ${ASOF}"

if [[ -n "${ADR_CLI:-}" ]]; then
  echo ""
  echo "==> Using the prebuilt adrkit CLI at ${ADR_CLI}"
  if [[ ! -f "${ADR_CLI}" ]]; then
    echo "error: ADR_CLI=${ADR_CLI} does not exist" >&2
    exit 1
  fi
  ADR_CLI="$(cd "$(dirname "${ADR_CLI}")" && pwd)/$(basename "${ADR_CLI}")"
else
  echo ""
  echo "==> Fetching adrkit at pinned commit ${ADRKIT_REF} (shallow, no full clone)"
  mkdir -p "${WORKDIR}/adrkit"
  git -C "${WORKDIR}/adrkit" init --quiet
  git -C "${WORKDIR}/adrkit" remote add origin "${ADRKIT_REPO}"
  git -C "${WORKDIR}/adrkit" fetch --quiet --depth 1 origin "${ADRKIT_REF}"
  git -C "${WORKDIR}/adrkit" checkout --quiet FETCH_HEAD
  RESOLVED_SHA="$(git -C "${WORKDIR}/adrkit" rev-parse HEAD)"
  if [[ "${RESOLVED_SHA}" != "${ADRKIT_REF}" ]]; then
    echo "error: resolved commit ${RESOLVED_SHA} does not match pinned ref ${ADRKIT_REF}" >&2
    exit 1
  fi
  echo "==> Building adrkit"
  (cd "${WORKDIR}/adrkit" && bun install --frozen-lockfile >/dev/null && bun run build >/dev/null)
  ADR_CLI="${WORKDIR}/adrkit/packages/cli/dist/index.js"
fi

echo ""
echo "==> Regenerating the reports at the pinned commit"
# Written exactly as the published recipe writes them: the command's verbatim
# stdout, no reformatting. Any reshaping here would mean the committed file is
# this script's rendering of adrkit's output rather than adrkit's output.
#
# Generated from the repository root with a RELATIVE --dir, and both matter.
# `sourcePath` is resolved against the process cwd rather than against --dir, and
# `corpusFingerprint` is computed over those paths, so the same 15 files produce
# a different report from a different working directory -- observed at this pin:
# cwd=<root> gives fingerprint 1664c5af…, cwd=<root>/scripts gives 3e00b654…,
# cwd=/tmp gives 66bf9f30…. Without this cd, running the script from anywhere
# but the root would report the committed file as stale when nothing had changed.
# See README.md, "corpusFingerprint is cwd-dependent".
cd "${REPO_ROOT}"
bun "${ADR_CLI}" lint --dir docs/adr --json > "${WORKDIR}/lint.json"
bun "${ADR_CLI}" queue --dir docs/adr --as-of "${ASOF}" \
  --format json > "${WORKDIR}/queue.json"

echo ""
echo "==> Asserting the committed reports are current"
for name in lint queue; do
  committed="${REPORT_DIR}/${name}.json"
  if [[ ! -f "${committed}" ]]; then
    fail "CURRENT-${name}" ".adrkit/${name}.json is missing"
    continue
  fi
  if diff -u "${committed}" "${WORKDIR}/${name}.json" > "${WORKDIR}/${name}.diff"; then
    pass "CURRENT-${name}" ".adrkit/${name}.json matches a regeneration at ${ADRKIT_REF:0:8}"
  else
    fail "CURRENT-${name}" ".adrkit/${name}.json is stale; regenerate it"
    sed 's/^/    /' "${WORKDIR}/${name}.diff" >&2
  fi
done

echo ""
echo "==> Asserting the fields the badges dereference"
# The badge URLs select `$.checked` and `$.totalItems`. shields.io renders a
# missing key as `no result` and a non-numeric value as that value's text, so
# both the presence and the JSON type are asserted. `type == "number"` also
# rejects a JSON boolean, which jq's `numbers` filter would too but which a
# truthiness test would accept.
check_int() {
  local file="$1" query="$2" id="$3"
  local observed
  if [[ ! -f "${file}" ]]; then
    fail "${id}" "${query} cannot be read (${file##*/} is missing)"
    return 0
  fi
  observed="$(jq -r "${query} | if type == \"number\" and . == floor then \"int:\\(.)\" else \"bad:\\(type)\" end" \
    "${file}" 2>/dev/null || echo "bad:unparseable")"
  case "${observed}" in
    int:*) pass "${id}" "${query} is an integer (${observed#int:})" ;;
    *)     fail "${id}" "${query} is not an integer (${observed})" ;;
  esac
}
check_int "${REPORT_DIR}/lint.json"  '.checked'    "BADGE-checked"
check_int "${REPORT_DIR}/queue.json" '.totalItems' "BADGE-totalItems"

# A corpus that does not lint is not a corpus worth publishing a count for.
# Guarded rather than assumed readable: an unreadable report must fail as an
# assertion, not abort the script under `set -e` and skip the ones after it.
FINDINGS="$(jq -r '.findings | length' "${REPORT_DIR}/lint.json" 2>/dev/null || echo "unreadable")"
if [[ "${FINDINGS}" == "0" ]]; then
  pass "BADGE-clean" "the published lint report carries no findings"
else
  fail "BADGE-clean" "the published lint report carries ${FINDINGS} findings"
fi

echo ""
if (( FAILURES > 0 )); then
  echo "error: ${FAILURES} badge-report assertion(s) failed" >&2
  echo "Regenerate with:" >&2
  echo "  adr lint  --dir docs/adr --json                       > .adrkit/lint.json" >&2
  echo "  adr queue --dir docs/adr --as-of ${ASOF} --format json > .adrkit/queue.json" >&2
  exit 1
fi
echo "Badge report validation OK: 5 assertions passed (adrkit@${ADRKIT_REF}, as-of ${ASOF})."
